config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  require Rails.root.join('lib', 'subdomain.rb')
  # ELBヘルスチェック用
  get 'health' => 'health_check#health'

  constraints ExcludedSubdomainConstraint do
    root to: redirect('/movie')
    # ログイン関連
    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    delete 'logout' => 'sessions#destroy'
    # 動画
    resources :movies, only: [:index, :new, :create, :destroy], controller: 'videos'
    # 動画ステータス変更
    put 'movie/:id/status' => 'videos#change_status'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tenant.rb
class Tenant < ApplicationRecord
  has_secure_password
  before_create :create_remember_token
  after_create :create_tenant

  validates :password, length: { in: 6..20 }

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.encrypt(token)
    Digest::SHA256.hexdigest(token.to_s)
  end

  private

  # User生成時、before_createコールバックから呼び出す。
  def create_remember_token
    self.remember_token = Tenant.encrypt(Tenant.new_remember_token)
  end

  def create_tenant
    Apartment::Tenant.create(name)
  end
end

app/models/video.rb
class Video < ApplicationRecord
  has_one :video_capacity
  has_many :video_item_links, dependent: :destroy
  accepts_nested_attributes_for :video_item_links, allow_destroy: true

  validates_associated :video_item_links

  with_options presence: true do
    validates :item_url, uniqueness: true
    validates :file
  end

  mount_uploader :file, VideoUploader

  enum status: {published: 0, closed: 1}
end

app/models/video_capacity.rb
class VideoCapacity < ApplicationRecord
  belongs_to :video

  def self.get_monthly_capacity
    now = Time.zone.now

    target_month = Range.new(
        now.beginning_of_month,
        now.end_of_month
    )

    VideoCapacity.where(created_at: target_month).sum(:capacity) / 1.gigabyte
  end
end

app/models/video_item_link.rb
class VideoItemLink < ApplicationRecord
  belongs_to :video

  validate :both_inputs?

  private

  def both_inputs?
    unless name.present? && url.present?
      errors.add(:name, '関連アイテムリンクは両方入力してください')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/health_check_controller.rb
class HealthCheckController < ApplicationController
  def health
    render plain:'ok'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :set_tenant, only: [:create]

  def new
  end

  def create
    if @tenant.authenticate(session_params[:password])
      login_in @tenant
      redirect_to :controller => 'videos', :action => "index"
    else
      flash.now[:error] = t('sessions.errors.login_error')
      render 'new'
    end
  end

  def destroy
    log_out if login_in?
    redirect_to login_path
  end

  private

  def set_tenant
    @tenant = Tenant.find_by!(email: session_params[:email].downcase)
  rescue
    flash.now[:error] = t('sessions.errors.login_error')
    render action: 'new'
  end

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :require_login_in!

  def index
    @video = Video.all.page(params[:page]).per(10)
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)
    @video.video_capacity = VideoCapacity.new(capacity: @video.file.size)

    if @video.save
      # todo videw側表示
      flash[:success] = "動画を投稿しました。"
      redirect_to :controller => 'videos', :action => "index"
    else
      # todo videw側表示
      flash.now[:danger] = "動画の投稿に失敗しました。"
      render :new
    end
  end

  def destroy
    @video = Video.find(params[:id])

    @video.destroy
    redirect_to :controller => 'videos', :action => "index"
  end

  def change_status
    @video = Video.find(params[:id])

    case @video.status
    when 'published'
      @video.closed!
    when 'closed'
      @video.published!
    else
      nil
    end
  end

  private

  def video_params
    params.require(:video).permit(:item_url, :file, :file_cache, :text, video_item_links_attributes: [:name, :url, :_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login_in(tenant)
    remember_token = Tenant.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    tenant.update_attribute(:remember_token, Tenant.encrypt(remember_token))
    @current_tenant = tenant
  end

  def log_out
    cookies.delete(:remember_token)
    @current_tenant = nil
  end

  def current_tenant
    remember_token = Tenant.encrypt(cookies[:remember_token])
    @current_tenant ||= Tenant.find_by(remember_token: remember_token)
  end

  def login_in?
    current_tenant.present? && request.subdomain == current_tenant.subdomain
  end

  def require_login_in!
    redirect_to :controller => 'sessions', :action => "new" unless login_in?
  end

end

app/views/layouts/_header.erb
<nav class="navbar is-white">
  <div class="container">

    <div class="navbar-brand">
      <a role="button" class="navbar-burger burger" data-target="topNav">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="topNav" class="navbar-menu">
      <div class="navbar-start">
        <a class="navbar-item has-text-centered" href="<%= new_movie_path %>" style="display: block">
          <p style="font-size: 2rem">
            <%= icon('far', 'play-circle') %>
          </p>
          <p>動画登録</p>
        </a>
      </div>

      <div class="navbar-end">
        <div class="navbar-item">
          <div>
            <% all_capacity = VideoCapacity.get_monthly_capacity %>
            <p class="mb-1"><%= 1000 - all_capacity %>GB利用可能 / 1,000GB</p>
            <progress class="progress is-primary navbar-capacity-progress" value="<%= all_capacity %>" max="1000"></progress>
          </div>
        </div>
      </div>
    </div>

  </div>
</nav>

<script>
    (function () {
        var burger = document.querySelector('.burger');
        var menu = document.querySelector('#' + burger.dataset.target);
        burger.addEventListener('click', function () {
            burger.classList.toggle('is-active');
            menu.classList.toggle('is-active');
        });
    })();
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) || 'touchup' %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= yield :css %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/videos/_form.erb
<div class="box video-form">
  <%= form_with model: @video, url: {controller: 'videos', action: 'create'}, local: true do |f| %>
    <div class="field">
      <div class="control">
        <div class="columns is-vcentered">
          <div class="column is-one-fifth">
            <%= f.label :item_url, '商品ページURL' %>
            <span class="tag">必須</span>
          </div>
          <div class="column">
            <%= f.text_field :item_url, class: 'input', type: 'url', placeholder: "商品ページURL", required: true %>
          </div>
        </div>
      </div>
    </div>

    <hr>

    <div class="field">
      <div class="control">
        <div class="columns is-vcentered">
          <div class="column is-one-fifth">
            <%= f.label :file, '動画データ' %>
            <span class="tag">必須</span>
          </div>
          <div class="column">
            <!-- movはsafariじゃないと再生できない-->
            <%# if @video.file.present? || @video.file_cache.present? %>
              <%# if @video.file %>
                <%#= video_tag(@video.file, :controls => true) %>
              <%# else %>
                <%#= video_tag(@video.file_cache, :controls => true) %>
              <%# end %>
            <%# end %>
            <div class="textarea choose-file-area has-text-centered">
              <!-- 動画があるときに挙動 file file_cacheにあれば -->
              <p class="play-icon"><%= icon('far', 'play-circle') %></p>
              <p class="has-text-weight-bold mb-1">ドラッグ＆ドロップで画像を追加する</p>
              <label class="cursor-pointer">
                <span class="button is-primary is-outlined has-text-weight-bold px-6">＋画像を選択</span>
                <%= f.file_field :file, accept: 'video/*', style: 'display: none;', type: "file", required: true %>
              </label>
              <%= f.hidden_field :file_cache %>
            </div>
            <div class="message mt-3">
              <div class="message-body">
                <ul>
                  <li>※動画登録は1つのみです</li>
                  <li>※推奨サイズは横1280px縦720pxです</li>
                  <li>※1GB以内の動画ファイルを用意してください</li>
                  <li>※対応ファイル：MOV、MPEG4、MP4</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <div class="columns is-vcentered">
          <div class="column is-one-fifth">
            <%= f.label :video_item_links, '関連アイテムリンク' %>
          </div>
          <div class="column">
            <div id="link-association-insertion-point">
              <%= f.fields_for :video_item_links do |item_link| %>
                <%= render 'video_item_link_fields', f: item_link %>
              <% end %>
            </div>

            <div class="columns is-light">
              <div class="column is-narrow">
                <%= link_to_add_association 'アイテムリンク追加', f, :video_item_links,
                                            class: 'button is-primary',
                                            data: {
                                                association_insertion_node: '#link-association-insertion-point',
                                                association_insertion_method: 'append'}
                %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <div class="columns is-vcentered">
          <div class="column is-one-fifth">
            <%= f.label :text, 'テキスト入力' %>
          </div>
          <div class="column">
            <%= f.text_area :text, class: 'textarea', placeholder: "コーディネートのアドバイスや商品の補足テキストを記載しましょう。" %>
          </div>
        </div>
      </div>
    </div>

    <% if @video.errors.any? %>
      <div class="columns is-centered">
        <div class="column is-half">
          <div class="message is-danger mt-3">
            <div class="message-body">
              <ul>
                <%# binding.pry %>
                <% @video.errors.full_messages.each do |e| %>
                  <li><%= e %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    <% end %>

    <div class="field is-grouped is-grouped-centered">
      <div class="control">
        <%= link_to movies_path do %>
          <%= button_tag 'キャンセル', type: :button, class: "level-item button is-block is-light px-6" %>
        <% end %>
      </div>
      <div class="control">
        <%= f.submit "登録する", data: {confirm: "動画を登録しますか？"}, class: "level-item button is-block is-primary px-6" %>
      </div>
    </div>

  <% end %>

</div>

app/views/videos/_video_item_link_fields.erb
<div class="columns nested-fields">
  <div class="column">
    <%= f.text_field :name, class: 'input', type: 'text', placeholder: "商品名" %>
  </div>
  <div class="column">
    <%= f.text_field :url, class: 'input', type: 'url', placeholder: "URL" %>
  </div>
  <div class="column is-narrow">
    <%= link_to_remove_association '削除', f, class: 'button is-danger' %>
  </div>
</div>

app/views/videos/index.html.erb
<% provide(:title, "動画管理") %>

<%= render partial: 'layouts/header' %>

<section class="hero is-fullheight video-index">
  <div class="hero-head">
    <div class="container my-6">
      <div class="level">
        <div class="level-left">
          <h1 class="level-item title">動画管理</h1>
        </div>
        <div class="level-right">
          <%= link_to "＋動画を登録する", new_movie_path, class: 'level-item button is-primary px-6' %>
        </div>
      </div>
      <div class="box">
        <div class="table-container">
          <table class="table is-fullwidth is-hoverable">
            <thead>
            <tr>
              <th>ID</th>
              <th>商品URL</th>
              <th>動画</th>
              <th>公開状態</th>
              <th>削除</th>
            </tr>
            </thead>
            <tbody>
            <% @video.each do |v| %>
              <tr>
                <th class="is-vcentered"><%= v.id %></th>
                <td class="is-vcentered"><a href="<%= v.item_url %>"><p><%= v.item_url %></p></a></td>
                <td class="is-vcentered">
                  <video width="200" preload="none" controls
                         src="<%= v.file %>">
                  </video>
                </td>
                <td class="is-vcentered">
                  <div id="status-<%= v.id %>" class="switch-area <%= v.published? ? 'is-active' : '' %>">
                    <%= link_to("/movie/#{v.id}/status", data: {confirm: '公開状態を変更しますか？'}, method: :put, class: "", remote: true) do %>
                      <label><span></span></label>
                      <div class="sw-img"></div>
                    <% end %>
                  </div>
                </td>
                <td class="is-vcentered">
                  <%= link_to "/movie/#{v.id}", :method => :delete do %>
                    <p class="delete"></p>
                  <% end %>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>

      </div>
      <%= paginate @video %>
    </div>
  </div>
</section>

<script>
    $(function () {
        const sa = $(".switch-area")
        sa.on("ajax:success", function (event) {
            $(event.currentTarget).toggleClass("is-active");
        })
        sa.on("ajax:error", function () {
            alert('更新に失敗しました')
        })
    })
</script>

app/views/videos/new.html.erb
<% provide(:title, "動画登録") %>


<section class="hero is-fullheight">
  <div class="hero-head">
    <div class="container my-6">
      <div class="breadcrumb has-succeeds-separator mb-2" aria-label="breadcrumbs">
        <ul>
          <li><a href="<%= movies_path %>">動画管理</a></li>
          <li class="is-active"><a href="#" aria-current="page">動画登録</a></li>
        </ul>
      </div>
      <p class="title">動画登録</p>

      <%= render partial: 'form' %>
    </div>
  </div>
</section>